disabled_rules:
  - trailing_whitespace
  - line_length
  - force_cast
  - force_try

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping

included:
  - TrustScan

excluded:
  - TrustScan/TrustScanTests
  - TrustScan/build
  - .build

line_length:
  warning: 120
  error: 160

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 60
  error: 100

cyclomatic_complexity:
  warning: 10
  error: 20

identifier_name:
  min_length: 2
  max_length: 40